### ISSUE TITLE
Check for newer version and notify user if a new version is available.

### ISSUE THREAD

**Issue by kjjuno** [kjjuno/GitDepend#103]
Use github api to check releases

**Comment by pdubb29** [comment]
So with this feature, would you like it to be a new command that we add?

I'll be using this as a reference:
https://developer.github.com/v3/repos/releases/
and using the latest release api call.

**Comment by kjjuno** [comment]
I think I would like this to run along with the help page. This will give users the overall help for how to use the program, and then also give them an indication that a newer version exists.

**Comment by kjjuno** [comment]
Please use http://restsharp.org/ to access the api

**Comment by pdubb29** [comment]
https://github.com/kjjuno/GitDepend/pull/115
